drivers: hv: dxgkrnl: simplify eventfd_signal()
drivers/hv/dxgkrnl/dxgmodule.c: In function ‘signal_host_cpu_event’:
drivers/hv/dxgkrnl/dxgmodule.c:174:17: error: too many arguments to function ‘eventfd_signal’
  174 |                 eventfd_signal(event->cpu_event, 1);
      |                 ^~~~~~~~~~~~~~
In file included from drivers/hv/dxgkrnl/dxgmodule.c:15:
./include/linux/eventfd.h:87:20: note: declared here
   87 | static inline void eventfd_signal(struct eventfd_ctx *ctx)
      |                    ^~~~~~~~~~~~~~

* Pre commit 3652117

Signed-off-by: 0wnerDied <z1281552865@gmail.com>